spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_demo?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: Woshij8dan!
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 18000000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名
  type-aliases-package: edu.seu.server.pojo
  # 关闭自动驼峰命名
  configuration:
    map-underscore-to-camel-case: false
# mybatis日志
logging:
  level:
    edu.seu.server.mapper: debug
# jwt配置
jwt:
  # 存储jwt的请求头
  tokenHeader: Authorization
  # JWT加密使用的密钥(secret盐)
  secret: yeb-secret
  # token过期时间
  expiration: 604800
  # JWT令牌开头
  tokenHead: Bearer
