url: 127.0.0.1:${server.port}
server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb_demo?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: Woshij8dan!
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 18000000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    timeout: 10000ms
    host: 127.0.0.1 # 测试环境
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 1024
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
  rabbitmq:
    username: admin
    password: Woshij8dan!
    host: 127.0.0.1
    port: 5672
    # 开启消息确认回调
    publisher-confirm-type: correlated
    # 开启消息失败回调
    publisher-returns: true

# 消息队列名称配置
message-queue:
  confirm-queue-name: mail.queue
  confirm-exchange-name: mail.exchange
  confirm-routing-key-name: mail.welcome

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名
  type-aliases-package: edu.seu.server.pojo
  # 关闭自动驼峰命名
  configuration:
    map-underscore-to-camel-case: false
# mybatis日志
logging:
  level:
    edu.seu.server.mapper: debug
# jwt配置
jwt:
  # 存储jwt的请求头
  tokenHeader: Authorization
  # JWT加密使用的密钥(secret盐)
  secret: yeb-secret
  # token过期时间
  expiration: 6048000
  # JWT令牌开头
  tokenHead: Bearer

#websocket配置
auth-token:
  header-name: Auth-Token